### ISSUE TITLE
Bug testing

### ISSUE THREAD

**Issue by jamwalab** [uot-project-grp/project01-calorie-tracker#47]
* Test for bugs before final submission

**Comment by ankurshahi80** [comment]
Test Scripts: When the user launches the page the first time, they are presented with the registration page

![](https://files.slack.com/files-pri/T01SCV851C5-F0245AW724A/screen_shot_2021-06-06_at_10.29.21_am.png)

**Comment by ankurshahi80** [comment]
Test Script: 

1. The user is presented with the registration page to include
- Name
- Initials
- Gender
- Weight (must me numerical)
- Height (must be numerical)

2. The user must include all the information to proceed.

Result: Worked as expected.
<img width="1958" alt="Screen Shot 2021-06-06 at 10 32 45 AM" src="https://user-images.githubusercontent.com/79622822/120929659-da606f80-c6b7-11eb-9a11-6410860acab1.png">

**Comment by ankurshahi80** [comment]
Test: 

1. The user can set the daily calorie goal.
2. Select food from the search list
3. Add food manually 
4. The app accepts both the entries and updates Progress, Calories consumed and the graph below.

Result: Worked as expected.
<img width="977" alt="Screen Shot 2021-06-06 at 10 46 43 AM" src="https://user-images.githubusercontent.com/79622822/120929772-61154c80-c6b8-11eb-87bb-4d0d89981c6a.png">

**Comment by ankurshahi80** [comment]
Test:
1. Uses the users location and searched the local weather to recommend physical activities for the current day and the next day.

Result: Works as expected.
<img width="1106" alt="Screen Shot 2021-06-06 at 10 35 44 AM" src="https://user-images.githubusercontent.com/79622822/120929857-b6e9f480-c6b8-11eb-9324-28e470c8cfc1.png">
<img width="987" alt="Screen Shot 2021-06-06 at 10 41 02 AM" src="https://user-images.githubusercontent.com/79622822/120929863-bc473f00-c6b8-11eb-80dd-0a0e302f4f72.png">

**Comment by ankurshahi80** [comment]
Test: Multiple user can register on the app by clicking on the User Initials.

Result: Works as expected.
<img width="246" alt="Screen Shot 2021-06-06 at 10 57 09 AM" src="https://user-images.githubusercontent.com/79622822/120930143-1f85a100-c6ba-11eb-827b-0047769349f7.png">

**Comment by ankurshahi80** [comment]
Test: Responsiveness

1. The app scales to fit smaller screen sizes: mobile and tablet

Result: Fails
